# Generated by Django 5.0.2 on 2024-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.TextField(verbose_name='Basket'),
        ),
    ]
